name: Build WebApp and execute Karate tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: install mariadb
      uses: getong/mariadb-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'db' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'password' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'password'
    - name: Check Java version 
      run: java -version && pwd && ls -al
    - name: Run Karate test
      run: gradle test
      env:
        ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
