name: packer

on:
  pull_request:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer format and validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: Run `packer init`
        id: init
        run: "packer init ./WebappAMI.pkr.hcl"

      - name: Run `packer format`
        run: "packer fmt ./WebappAMI.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./WebappAMI.pkr.hcl"