name: Build and generate AMI

on:
  pull_request:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer build and generate AMI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build with Gradle
        run: ./gradlew clean build -xTest

      - name: Run karate test
        run: /.gradlew test
        env:
          ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}

      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: Run `packer build`
        run: "packer build WebappAMI.pkr.hcl"
